version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./backend/temp_uploads:/app/temp_uploads
    environment:
      - CHROMA_DB_PATH=/app/chroma_db
      - TEMP_UPLOAD_PATH=/app/temp_uploads
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: ./backend
    command: celery -A celery_worker worker --loglevel=info
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./backend/temp_uploads:/app/temp_uploads
    depends_on:
      - redis
      - backend